---
- name: Check unpartitioned space
  shell: /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: unpartitioned
  changed_when: false
  failed_when: unpartitioned.stderr != ""

- name: Expand filesystem to fill disk
  command: raspi-config --expand-rootfs
  when: unpartitioned.stdout != "0.00GB"
  notify:
  - Restart
  - Wait for restart to finish

- meta: flush_handlers
